# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2024-07"

[[extensions]]
name = "Compare At Price"
handle = "compare-at-price"
type = "ui_extension"


# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/CompareAtPrice.tsx"
target = "purchase.checkout.cart-line-item.render-after"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
# network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

[extensions.settings]
[[extensions.settings.fields]]
key = "message"
type = "single_line_text_field"
name = "Message"
description = "Eg: Compare at price"

[[extensions.settings.fields]]
key = "fontSize"
type = "single_line_text_field"
name = "Font Size"
description = ""
[[extensions.settings.fields.validations]]
name = "choices"
value = '["extraSmall", "small", "base", "medium", "large", "extraLarge"]'

[[extensions.settings.fields]]
key = "alignment"
type = "single_line_text_field"
name = "Alignment"
description = ""
[[extensions.settings.fields.validations]]
name = "choices"
value = '["left", "right"]'

[[extensions.settings.fields]]
key = "appearance"
type = "single_line_text_field"
name = "Text Color"
description = ""
[[extensions.settings.fields.validations]]
name = "choices"
value = '["base", "accent", "decorative", "interactive", "subdued", "info", "success", "warning", "critical", "monochrome"]'

[[extensions.settings.fields]]
key = "isShowStrikethrough"
type = "boolean"
name = "Show Strikethrough"
description = ""

[[extensions.settings.fields]]
key = "isShowPercentage"
type = "boolean"
name = "Show Discount Percentage?"
description = ""
