# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b22f7f2d52c32c063c914c669e077e11"
name = "ca-delivery-customizations"
handle = "ca-delivery-customizations"
application_url = "https://african-even-div-rebound.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "emma-test-checkout-extensions.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_delivery_customizations,write_products"

[auth]
redirect_urls = [
  "https://african-even-div-rebound.trycloudflare.com/auth/callback",
  "https://african-even-div-rebound.trycloudflare.com/auth/shopify/callback",
  "https://african-even-div-rebound.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
