# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8753c10c6e70259ab4a63c3e40b5ae3d"
name = "Ca Checkout Customizations"
handle = "ca-checkout-customizations"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "emma-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms,write_delivery_customizations,write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
