name: PR Freshness /sync-live-here ≤ 15m

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, edited]
    branches: [main]

permissions:
  pull-requests: read
  issues: read

concurrency:
  group: pr-freshness-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  freshness:
    name: freshness
    runs-on: ubuntu-latest
    steps:
      - name: Check /sync-live-here within last 15 minutes
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const { data: comments } = await github.rest.issues.listComments({
              ...context.repo,
              issue_number: prNumber,
              per_page: 100,
              sort: 'created',
              direction: 'desc'
            });
            const slash = comments.find(c => typeof c.body === 'string' && c.body.trim().startsWith('/sync-live-here'));
            if (!slash) {
              core.setFailed("Missing `/sync-live-here`. Please comment `/sync-live-here` within the last 15 minutes before merging.");
              return;
            }
            const created = new Date(slash.created_at).getTime();
            const ageSec = Math.floor((Date.now() - created) / 1000);
            const MAX = 15 * 60; // 15 phút
            if (ageSec > MAX) {
              core.setFailed(`\`/sync-live-here\` is stale (${Math.floor(ageSec/60)} min ago). Please run it again.`);
              return;
            }
            core.info("Freshness OK (≤ 15 minutes).")
