name: Revert last release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name'
        required: true
        default: null

jobs:
  revert_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}
          fetch-depth: 0
      - name: Revert pushed commit
        run: |
          target_tag = git tag -l "$ref"
          
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git revert --no-edit HEAD
          git push
