name: Setup Shopify CLI

on:
  workflow_call:
    outputs:
      cache-key:
        description: "Cache key for Shopify CLI"
        value: "shopify-cli-cache"
env:
  CACHE_KEY: shopify-cli-cache

jobs:
  restore-cache:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.restore-cache.outputs.cache-hit == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore cache
        id: "restore-cache"
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ env.CACHE_KEY }}

  install-shopify-cli:
    needs: "restore-cache"
    if: restore-cache.outputs.cache-hit != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Shopify CLI
        run: npm install -g @shopify/cli@latest

      - name: Cache Node Modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ CACHE_KEY }}

