name: Shopify Sync Theme
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]

jobs:
  setup-shopify-cli:
    uses: ./.github/workflows/setup-shopify-cli.yml

  check-for-changes:
    needs: setup-shopify-cli
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: ~/lib/node_modules
          key: ${{ needs.setup-shopify-cli.outputs.cache-key }}
      - name: Pull Live Theme
        env:
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          SHOPIFY_FLAG_STORE: ${{ vars.SHOPIFY_FLAG_STORE }}
        run: |
          shopify theme pull \
            -s "$SHOPIFY_FLAG_STORE" \
            --password "$SHOPIFY_CLI_THEME_TOKEN" \
            -l
      - name: Commit and push if theme changed
        run: |
          git config --global user.name "Shopify Bot"
          git config --global user.email "shopify-bot@emma-sleep.com"

          # Check if there are any changes
          if git diff --quiet && git diff --cached --quiet; then
            echo "✅ No theme changes detected."
            exit 0
          fi

          git add -A
          timestamp=$(date -u "+%Y-%m-%d %H:%M:%S UTC")
          git commit -m "chore(bot): Sync LIVE theme at ${timestamp}"
          git push origin ${{ github.head_ref }}

