name: Shopify Sync Theme
on:
  workflow_call:
  workflow_dispatch:
jobs:
  theme-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli@latest

      - name: Pull Live Theme
        env:
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          SHOPIFY_FLAG_STORE: ${{ vars.SHOPIFY_FLAG_STORE }}
        run: |
          shopify theme pull \
            -s "$SHOPIFY_FLAG_STORE" \
            --password "$SHOPIFY_CLI_THEME_TOKEN" \
            --path "theme" \
            -l


      - name: Verify theme changed
        id: verify-theme-changed
        run: |
          # Check if there are any changes
          if git diff --quiet && git diff --cached --quiet; then
            echo "✅ No theme changes detected."
            echo "hasChanged=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "hasChanged=true" >> $GITHUB_OUTPUT


      - name: Commit and push changed files to a temporary branch
        if: ${{ steps.verify-theme-changed.outputs.hasChanged == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "Shopify Bot"
          git config --global user.email "shopify-bot@emma-sleep.com"

          # Create unique branch name with timestamp
          timestamp=$(date -u "+%Y%m%d-%H%M%S")
          BRANCH_NAME="sync-live-theme-${timestamp}"

          echo "Creating branch: $BRANCH_NAME"

          # Create and checkout new branch from main
          git checkout -b "$BRANCH_NAME"

          # Commit the theme changes
          git add -A
          commit_timestamp=$(date -u "+%Y-%m-%d %H:%M:%S UTC")
          git commit -m "system(bot): Sync LIVE theme at ${commit_timestamp}"

          # Push the new branch
          git push origin "$BRANCH_NAME"

      - name: Create Pull Request
        run: |
          # Create pull request
          gh pr create \
            --title "🤖 Sync LIVE theme at ${commit_timestamp}" \
            --body "Automated sync of live theme changes from Shopify store." \
            --base main \
            --head "$BRANCH_NAME"

          # Get PR number for rebase and merge
          PR_NUMBER=$(gh pr view --json number --jq '.number')

          # Rebase and merge PR
          gh pr merge "$PR_NUMBER" \
            --rebase \
            --delete-branch \
            --admin
