name: Shopify Sync Theme
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli@latest

      - name: Pull Live Theme
        env:
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          SHOPIFY_FLAG_STORE: ${{ vars.SHOPIFY_FLAG_STORE }}
        run: |
          shopify theme pull \
            -s "$SHOPIFY_FLAG_STORE" \
            --password "$SHOPIFY_CLI_THEME_TOKEN" \
            --path "theme" \
            -l

      - name: Commit and push if theme changed
        run: |
          git config --global user.name "Shopify Bot"
          git config --global user.email "shopify-bot@emma-sleep.com"

          # Check if there are any changes
          if git diff --quiet && git diff --cached --quiet; then
            echo "✅ No theme changes detected."
            exit 0
          fi

          # Get current branch name
          CURRENT_BRANCH="${{ github.head_ref }}"
          echo "Working on branch: $CURRENT_BRANCH"

          # Fetch latest main branch
          git fetch origin main

          # Commit the changes
          git add -A
          timestamp=$(date -u "+%Y-%m-%d %H:%M:%S UTC")
          git commit -m "system(bot): Sync LIVE theme at ${timestamp}"

          # Ensure we're on the correct branch
          git checkout "$CURRENT_BRANCH"

          # Rebase onto main to make sync commit the first commit
          git rebase origin/main

          # Force push the rebased branch
          git push --force-with-lease origin "$CURRENT_BRANCH"

