name: Shopify Sync Theme
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]
jobs:
  setup-shopify-cli:
    uses: ./.github/workflows/setup-shopify-cli.yml
  check-for-changes:
    needs: setup-shopify-cli

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Restore node modules cache
        uses: actions/cache@v4
        with:
          path: ~/.npm # or node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Pull Live Theme
        env:
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          SHOPIFY_FLAG_STORE: ${{ vars.SHOPIFY_FLAG_STORE }}
        run: |
          shopify theme pull \
            -s "$SHOPIFY_FLAG_STORE" \
            --password "$SHOPIFY_CLI_THEME_TOKEN" \
            -l
      - name: Commit and push if theme changed
        run: |
          cd theme
          git config user.name = "Shopify Bot"
          git config user.email = "shopify-bot@emma-sleep.com"
          
          if [[ -z $(git status) ]]; then
            echo "✅No theme changes detected."
            exit 0
          fi
          
          git add -A
          timestamp=$(date -u "+%Y-%m-%d %H:%M:%S UTC")
          git commit -m "(bot): Sync LIVE theme at ${timestamp}"
          git push

